import Head from "next/head";
import { useState, useEffect } from "react";
import styles from "../../styles/Home.module.css";
import hookStyles from "../../styles/Hooks.module.css";

function Counter({ initialCount }) {
  const [count, setCount] = useState(initialCount);
  return (
    <div className={hookStyles.counter}>
      <h2>Counter</h2>
      Count: {count}
      <button onClick={() => setCount(initialCount)}>Reset</button>
      <button onClick={() => setCount((prevCount) => prevCount - 1)}>-</button>
      <button onClick={() => setCount((prevCount) => prevCount + 1)}>+</button>
    </div>
  );
}

export default function App() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>useReducer()</h1>
        <Counter initialCount={42} />
      </main>
    </div>
  );
}
