import Head from "next/head";
import { useState, useEffect } from "react";
import styles from "../../styles/Home.module.css";
import hookStyles from "../../styles/Hooks.module.css";

function Counter({ initialCount }) {
  const [count, setCount] = useState(initialCount);
  const [fontSize, setFontSize] = useState(16);

  return (
    <div className={hookStyles.counter}>
      <span
        style={{
          fontSize: `${fontSize}px`,
          marginBottom: "1rem",
        }}
      >
        Count: {count}
      </span>
      <button onClick={() => setCount(initialCount)}>Reset</button>
      <button onClick={() => setCount(count - 1)}>Count - 1</button>
      <button onClick={() => setCount(count + 1)}>Count + 1</button>
      <button onClick={() => setFontSize(fontSize - 2)}>Fontsize - 2</button>
      <button onClick={() => setFontSize(fontSize + 2)}>Fontsize + 2</button>
    </div>
  );
}

export default function App() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>useReducer()</h1>
        <Counter initialCount={42} />
      </main>
    </div>
  );
}
