import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Test() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>This is a test</h1>
      </main>
    </div>
  );
}
